In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 

In [2]:
df = pd.read_csv("winequality-red.csv")

In [3]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
from pandas_profiling import ProfileReport

In [5]:
profile = ProfileReport(df, title = "pandas profile Report")
profile.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
import seaborn as sns
sns.scatterplot(data=df, x = "fixed acidity", y = "density")

<AxesSubplot:xlabel='fixed acidity', ylabel='density'>

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
new_data= scaler.fit_transform(df.drop(labels=['quality'], axis = 1))

In [8]:
new_data

array([[-0.52835961,  0.96187667, -1.39147228, ...,  1.28864292,
        -0.57920652, -0.96024611],
       [-0.29854743,  1.96744245, -1.39147228, ..., -0.7199333 ,
         0.1289504 , -0.58477711],
       [-0.29854743,  1.29706527, -1.18607043, ..., -0.33117661,
        -0.04808883, -0.58477711],
       ...,
       [-1.1603431 , -0.09955388, -0.72391627, ...,  0.70550789,
         0.54204194,  0.54162988],
       [-1.39015528,  0.65462046, -0.77526673, ...,  1.6773996 ,
         0.30598963, -0.20930812],
       [-1.33270223, -1.21684919,  1.02199944, ...,  0.51112954,
         0.01092425,  0.54162988]])

In [9]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [10]:
scale_data=pd.DataFrame(new_data)

In [11]:
scale_data

0         1         2         3         4         5         6   \
0    -0.528360  0.961877 -1.391472 -0.453218 -0.243707 -0.466193 -0.379133   
1    -0.298547  1.967442 -1.391472  0.043416  0.223875  0.872638  0.624363   
2    -0.298547  1.297065 -1.186070 -0.169427  0.096353 -0.083669  0.229047   
3     1.654856 -1.384443  1.484154 -0.453218 -0.264960  0.107592  0.411500   
4    -0.528360  0.961877 -1.391472 -0.453218 -0.243707 -0.466193 -0.379133   
...        ...       ...       ...       ...       ...       ...       ...   
1594 -1.217796  0.403229 -0.980669 -0.382271  0.053845  1.542054 -0.075043   
1595 -1.390155  0.123905 -0.877968 -0.240375 -0.541259  2.211469  0.137820   
1596 -1.160343 -0.099554 -0.723916 -0.169427 -0.243707  1.255161 -0.196679   
1597 -1.390155  0.654620 -0.775267 -0.382271 -0.264960  1.542054 -0.075043   
1598 -1.332702 -1.216849  1.021999  0.752894 -0.434990  0.203223 -0.135861   

            7         8         9         10  
0     0.558274  1.288643 -0.579207 -0.960246  
1     0.028261 -0.719933  0.128950 -0.584777  
2     0.134264 -0.331177 -0.048089 -0.584777  
3     0.664277 -0.979104 -0.461180 -0.584777  
4     0.558274  1.288643 -0.579207 -0.960246  
...        ...       ...       ...       ...  
1594 -0.978765  0.899886 -0.461180  0.072294  
1595 -0.862162  1.353436  0.601055  0.729364  
1596 -0.533554  0.705508  0.542042  0.541630  
1597 -0.676657  1.677400  0.305990 -0.209308  
1598 -0.666057  0.511130  0.010924  0.541630  

[1599 rows x 11 columns]

In [12]:
scale_data=pd.DataFrame(new_data, columns=['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'])

In [13]:
scale_data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0         -0.528360          0.961877    -1.391472       -0.453218  -0.243707   
1         -0.298547          1.967442    -1.391472        0.043416   0.223875   
2         -0.298547          1.297065    -1.186070       -0.169427   0.096353   
3          1.654856         -1.384443     1.484154       -0.453218  -0.264960   
4         -0.528360          0.961877    -1.391472       -0.453218  -0.243707   
...             ...               ...          ...             ...        ...   
1594      -1.217796          0.403229    -0.980669       -0.382271   0.053845   
1595      -1.390155          0.123905    -0.877968       -0.240375  -0.541259   
1596      -1.160343         -0.099554    -0.723916       -0.169427  -0.243707   
1597      -1.390155          0.654620    -0.775267       -0.382271  -0.264960   
1598      -1.332702         -1.216849     1.021999        0.752894  -0.434990   

      free sulfur dioxide  total sulfur dioxide   density        pH  \
0               -0.466193             -0.379133  0.558274  1.288643   
1                0.872638              0.624363  0.028261 -0.719933   
2               -0.083669              0.229047  0.134264 -0.331177   
3                0.107592              0.411500  0.664277 -0.979104   
4               -0.466193             -0.379133  0.558274  1.288643   
...                   ...                   ...       ...       ...   
1594             1.542054             -0.075043 -0.978765  0.899886   
1595             2.211469              0.137820 -0.862162  1.353436   
1596             1.255161             -0.196679 -0.533554  0.705508   
1597             1.542054             -0.075043 -0.676657  1.677400   
1598             0.203223             -0.135861 -0.666057  0.511130   

      sulphates   alcohol  
0     -0.579207 -0.960246  
1      0.128950 -0.584777  
2     -0.048089 -0.584777  
3     -0.461180 -0.584777  
4     -0.579207 -0.960246  
...         ...       ...  
1594  -0.461180  0.072294  
1595   0.601055  0.729364  
1596   0.542042  0.541630  
1597   0.305990 -0.209308  
1598   0.010924  0.541630  

[1599 rows x 11 columns]

In [14]:
from pandas_profiling import ProfileReport
profile = ProfileReport(scale_data, title="pandas profiling Report")
profile.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [15]:
from sklearn.preprocessing import RobustScaler
transform = RobustScaler()
transform_data= transform.fit_transform(df.drop(labels=['quality'], axis = 1))

In [16]:
transform_data

array([[-0.23809524,  0.72      , -0.78787879, ...,  1.05263158,
        -0.33333333, -0.5       ],
       [-0.04761905,  1.44      , -0.78787879, ..., -0.57894737,
         0.33333333, -0.25      ],
       [-0.04761905,  0.96      , -0.66666667, ..., -0.26315789,
         0.16666667, -0.25      ],
       ...,
       [-0.76190476, -0.04      , -0.39393939, ...,  0.57894737,
         0.72222222,  0.5       ],
       [-0.95238095,  0.5       , -0.42424242, ...,  1.36842105,
         0.5       ,  0.        ],
       [-0.9047619 , -0.84      ,  0.63636364, ...,  0.42105263,
         0.22222222,  0.5       ]])

In [17]:
transf_df = pd.DataFrame(transform_data, columns=['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'])

In [18]:
from pandas_profiling import ProfileReport
profile = ProfileReport(transf_df, title = "pandas profile report")
profile.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [19]:
x = scale_data
y = df["quality"]

In [20]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.33, random_state = 1)

In [21]:
from sklearn.svm import SVC

In [22]:
model=SVC()
model.fit(train_x, train_y)

SVC()

In [23]:
model.predict(test_x)

array([5, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 5, 7, 6, 5, 6, 5, 6, 5, 5, 6,
       5, 6, 5, 6, 6, 6, 5, 7, 6, 7, 5, 7, 5, 5, 5, 5, 7, 5, 6, 5, 5, 6,
       5, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 6, 6, 6, 6, 5, 6, 5, 5, 5, 5, 5,
       7, 6, 6, 7, 5, 6, 5, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 6, 5, 5, 6,
       5, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 6, 6, 6, 5,
       6, 6, 6, 6, 5, 7, 5, 5, 5, 5, 5, 7, 6, 5, 5, 6, 6, 5, 7, 6, 5, 5,
       6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 7, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 6, 5, 6, 5, 5, 6, 5,
       5, 5, 5, 5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5,
       5, 5, 6, 5, 6, 5, 7, 6, 5, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6,
       6, 5, 5, 5, 6, 6, 5, 6, 7, 5, 5, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 6,
       6, 5, 5, 7, 5, 5, 5, 5, 5, 5, 6, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6, 5,
       5, 6, 6, 5, 5, 6, 5, 6, 5, 7, 5, 6, 6, 6, 5, 5, 6, 5, 6, 5, 5, 6,
       5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6,

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
accuracy_score(test_y, model.predict(test_x))

0.6003787878787878

In [26]:
from sklearn.model_selection import GridSearchCV

In [30]:
param_grid={'C':[0.1,1,10,50,100,500], 'gamma':[1,0.5,0.1,0.01,0.001]}

ERROR! Session/line number was not unique in database. History logging moved to new session 215


In [31]:
grid=GridSearchCV(SVC(),param_grid, verbose=3, n_jobs=-1)

In [32]:
grid.fit(train_x, train_y)

Fitting 5 folds for each of 30 candidates, totalling 150 fits


GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 50, 100, 500],
                         'gamma': [1, 0.5, 0.1, 0.01, 0.001]},
             verbose=3)

In [33]:
grid.best_params_

{'C': 1, 'gamma': 0.5}

In [34]:
model_grid=SVC(C=1, gamma = 0.5)
model_grid.fit(train_x, train_y)

SVC(C=1, gamma=0.5)

In [35]:
model_grid.predict(test_x)

array([5, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6,
       5, 6, 5, 6, 6, 5, 5, 7, 6, 7, 5, 7, 5, 6, 5, 6, 6, 5, 6, 5, 5, 6,
       5, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 6,
       5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 7,
       5, 6, 5, 7, 5, 7, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5,
       6, 5, 5, 6, 5, 7, 5, 5, 5, 5, 5, 7, 6, 5, 5, 5, 6, 5, 6, 6, 5, 5,
       6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 7, 5, 5,
       6, 7, 7, 6, 6, 6, 7, 5, 5, 5, 6, 6, 6, 5, 5, 6, 6, 6, 5, 5, 6, 5,
       5, 5, 5, 5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6, 6, 6, 5,
       5, 5, 6, 5, 7, 5, 7, 6, 5, 5, 6, 6, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6,
       5, 5, 5, 5, 6, 6, 5, 6, 7, 5, 6, 6, 7, 6, 5, 5, 6, 5, 5, 5, 6, 6,
       7, 6, 5, 7, 5, 5, 5, 5, 5, 5, 6, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6, 5,
       5, 6, 6, 5, 5, 6, 5, 6, 5, 7, 5, 5, 6, 6, 5, 6, 6, 5, 5, 5, 5, 6,
       5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 7, 5, 5, 5,

In [36]:
accuracy_score(test_y, model_grid.predict(test_x))

0.6268939393939394